Repository vancado/vnc_interactive_image, pull requests merged in 2024-10, with the labels that each got.

#30 [FEATURE] Adjust github workflow
  .github/workflows/release-drafter.yml
Labels: feature

#31 [FEATURE] Adjust github workflow
  .github/workflows/release-drafter.yml
  Resources/Private/Partials/InfoboxNav.html
Labels: feature

#32 [FEATURE] Refactor github workflow
  .github/workflows/release-drafter.yml
Labels: feature

#33 [TASK] Adjust github workflow
  .github/workflows/release-drafter.yml
Labels: task

#34 [TASK] Refactor github workflow
  .github/workflows/release-drafter.yml
Labels: task

#35 [TASK] Adjust github workflows
  .github/workflows/release-drafter.yml
  .github/workflows/update-changelog.yml
Labels: feature

#36 [TASK] Adjust changelog workflow
  .github/workflows/update-changelog.yml
Labels: feature

#41 [TASK] Refactor release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: task

#43 [FEATURE] Refactor release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#44 [TASK] Remove fullscreen mode
  Resources/Private/Partials/InfoBox.html
  Resources/Private/Partials/InfoBoxNav.html
  Resources/Private/Partials/InfoboxNav.html
  Resources/Private/Partials/Popover.html
  Resources/Private/Templates/Show.html
  Resources/Private/src/scss/interactive-image.scss
  Resources/Public/Css/Frontend/interactive-image.css
  Resources/Public/Css/Frontend/interactive-image.css.map
  Resources/Public/JavaScript/interactive-image.js
Labels: feature

#45 [TASK] Refactor code
  Resources/Private/Partials/InfoboxNav.html
  Resources/Public/JavaScript/interactive-image.js
Labels: task

#46 [BUGFIX] Fix image condition
  Resources/Private/Partials/InfoBox.html
Labels: bug
